### ISSUE TITLE
Double Chests unsupported

### ISSUE THREAD

**Issue by AlfmanOO7** [TeamDiopside/Seamless#1]
Unsure if there are any plans to add support for double chests, seeing as it's a 'multi-block structure' and not a single block that's larger than a block.

Just a suggestion, seeing as they have separate textures for single and double chests.

**Comment by LarsMans64** [comment]
Thanks for your suggestion! I forgot about chests! Indeed, those aren't really bouble blocks as when you break one side, the other remains, but i could make a config option to enable those.

**Comment by LarsMans64** [comment]
Oh yeah I forgot about this issue, I decided to just include chests as it being not a real double block doesn't really matter at all

**Comment by AlfmanOO7** [comment]
Yeah, thanks for adding my suggestion :)
