### ISSUE TITLE
Suggestion: Waystones

### ISSUE THREAD

**Issue by stlouisn** [TeamDiopside/Seamless#10]
Another, probably popular, block that should be included in the mod is waystones

**Comment by LarsMans64** [comment]
Thanks for the suggestion, waystones will be supported in the next update!

**Comment by stlouisn** [comment]
Thank you, that works for the three waystones blocks, there are two more blocks that could also use same treatment:

``
  "blocks": [
    "#waystones:waystones",
    "#waystones:sharestones",
    "waystones:portstone"
  ],
``

**Comment by LarsMans64** [comment]
Ah thanks, I wasn't aware of the other ones

**Comment by stlouisn** [comment]
the third item in the list is not tagged since it does not have any variants. it will not work with #waystones:portstone and has to be waystones:portstone

**Comment by LarsMans64** [comment]
Yeah I noticed that, thanks
