### ISSUE TITLE
[1.20.1] Interaction with Farmer's Delight?

### ISSUE THREAD

**Issue by neutralboolean** [TeamDiopside/Seamless#11]
Certainly a bug, although not one that is having an appreciably ill effect on my game. Just thought y'all'd might want to know about it. Seems like its just spamming incessantly to console. I don't know if I've even seen rice (I'm testing modpack/KubeJS scripts in various new worlds) but I keep seeing this log spam. Easily in excess of 100,000 times in a few minutes of flying around in Creative. 

Running version 2.0.0 of this mod and 1.2.3 of Farmer's Delight with a bunch of other FD addons.
![image](https://github.com/TeamDiopside/Seamless/assets/10564237/6d252c54-3181-4476-93f0-9f12a587ad66)

**Comment by curryducker** [comment]
This has already been fixed for the next update :)
