### ISSUE TITLE
[Feature Request] Render through blocks

### ISSUE THREAD

**Issue by TheFurryDevil** [TeamDiopside/Seamless#12]
Not sure if this is possible in a compatible way (keeping shaderpacks able to modify the outline without issues),
but it'd be great if you could add an option for making the outline render on top of everything.
I think that means temporarily disabling depth testing? Sounds trivial but I have too little experience with Minecraft internals.

**Comment by LarsMans64** [comment]
Changing the rendering of the outline is nog the goal of this mod, it's only about connecting them. If you want to change how they are rendered, you should search for another mod
