### ISSUE TITLE
[Bug]: Compatibility with Highlight

### ISSUE THREAD

**Issue by Spazer-Prime** [TeamDiopside/Seamless#15]
### Latest Version

- [X] I am running the latest version of the mod.

### What happened?

When Seamless is installed with Highlight (https://modrinth.com/mod/highlight) it undoes Highlight's changes.

### What version of Minecraft are you running?

1.20.1

### What mod loader are you using?

Fabric

**Comment by LarsMans64** [comment]
Sadly Highlight is incompatible with Seamless and there is not much that I can do. They use a different way of rendering the outlines.
