### ISSUE TITLE
[Suggestion]: Performance

### ISSUE THREAD

**Issue by SiverDX** [TeamDiopside/Seamless#16]
### What is your suggestion?

It's pretty high on the performance impact
(Most of the `Architectury` part probably also counts for this mod since it's all just `getModIds`)

![grafik](https://github.com/TeamDiopside/Seamless/assets/22003703/bed03eda-68f2-46a4-bb84-92b119c6ea4a)

![grafik](https://github.com/TeamDiopside/Seamless/assets/22003703/8b7648fa-3b8f-4800-821d-83378fc35d8a)

https://spark.lucko.me/5tdghCProp

**Comment by Luke100000** [comment]
Here another report from another modpack with similar/worse findings: https://spark.lucko.me/idxbjnuYS9?hl=4601
I checked `getModIds`, I can not spot something obviously slow (tho caching it might be appropriate) so I suspect the whole getBlocks() method is, for whatever reason, spammed.

**Comment by LarsMans64** [comment]
Yeah I had actually solved that already, and I am still working on improving performance even more
