### ISSUE TITLE
[Bug]: seamless-2.2.0-forge-1.19.2  Mixin [seamless-common.mixins.json:VideoSettingsScreenMixin] from phase [DEFAULT] in config [seamless-common.mixins.json] FAILED during APPLY

### ISSUE THREAD

**Issue by Minebrah** [TeamDiopside/Seamless#20]
### Latest Version

- [X] I am running the latest version of the mod.

### What happened?

The Game Crashed on startup

### What did you expect to happen?

To not crash

### What version of Minecraft are you running?

1.19.2

### What mod loader are you using?

Forge

### latest.log

https://gist.github.com/Minebrah/55e7d89d131e70a39cd66300ed9a22ce

**Comment by LarsMans64** [comment]
It works for me, so this is probably a compatibility issue. Could you try to find out which mod causes this crash?

**Comment by curryducker** [comment]
probably optifine

**Comment by Minebrah** [comment]
I reverted back to the version I was using before, version 2.1.1, and the game is working again like before. Whatever changes were made caused the crash. My personal modpack has over 800 mods so finding one incompatibility is a daunting task. I'll just stick to using seamless 2.1.1 . I'll try any future updates though.

**Comment by LarsMans64** [comment]
It should be fixed in the next update
