### ISSUE TITLE
[Bug]: Not working. Fabric 0.15.11-1.20.1

### ISSUE THREAD

**Issue by KyrDerz** [TeamDiopside/Seamless#26]
### Latest Version

- [X] I am running the latest version of the mod.

### What happened?

![image](https://github.com/TeamDiopside/Seamless/assets/110685473/30952fb5-248d-4dd7-8f21-865dc52ab493)
It just doesn't work at all.

### What version of Minecraft are you running?

1.20.1

### What mod loader are you using?

Fabric

### latest.log

https://gist.github.com/KyrDerz/39451ecccbf7ecbda88ddc316b1cf8a1

**Comment by LarsMans64** [comment]
Is the built in resource pack enabled?

**Comment by KyrDerz** [comment]
Well, now I feel silly. All works. Bedankt

**Comment by LarsMans64** [comment]
:)
