### ISSUE TITLE
Version 1.8.2 downloads as 1.9.2

### ISSUE THREAD

**Issue by Keoxxa** [TeamDiopside/Seamless#3]
Cannot run the mod with latest update as the mod downloads for 1.9.2 instead of 1.8.2, despite being listed as compatible on curse forge.
"latest supported game version: 1.8.2" downloads as 1.9.2
![wrong version](https://github.com/TeamDiopside/Seamless/assets/116791692/f8dc9554-6a0b-4f82-b5d2-5f6ee49248a1)

**Comment by LarsMans64** [comment]
Oh yeah sorry, I forgot about that. It will be fixed in the next update. 1.18.2 is compatible, but the mod thinks it's not.

**Comment by curryducker** [comment]
I don't know why there's an 1.18 tag because it's not supported yet

**Comment by curryducker** [comment]
Oh wait Lars completed this already GitHub didn't load that woops
