### ISSUE TITLE
Possibility of inclusion in LifeMC Studios

### ISSUE THREAD

**Issue by Nukecraft5419** [TeamDiopside/Seamless#4]
Hi I'm the CEO of the LifeMC Studios team where we are developing a modpack that is close to release we have been testing and we are going to put this mod in the modpack, and wanted to suggest a nice feature that would allow you to customise and colour outline then thickness and colour on all the blocks and also the backport to 1.18.2

**Comment by LarsMans64** [comment]
Hi! Sorry for not answering for three weeks, I have no clue how I didn't see this issue earlier. Thanks for using Seamless in your modpack! Configurable outlines would indeed be nice to have, however this mod is only for connecting outlines and there are already other mods made for it, like [Color Me Outlines](https://modrinth.com/mod/color-me-outlines). The backport to 1.18.2 will be published soon.

**Comment by Nukecraft5419** [comment]
True only that Color Me Outlines seems to be abandoned that's why I asked as soon as I see Seamless 1.18.2 I'll put the mod in the modpack so I do 1 commit for all 3 versions I'll send you the commit when I've done it so you know it's inserted

**Comment by LarsMans64** [comment]
1.18.2 is now released

**Comment by Nukecraft5419** [comment]
https://github.com/LifeMC-Studios/LifeMC/pull/202
