### ISSUE TITLE
[Feature Request] Configurable Connections

### ISSUE THREAD

**Issue by TheFurryDevil** [TeamDiopside/Seamless#6]
Basically, a system that let's users define rules for connecting the outline of arbitrary blocks using a few rules.
Something like:
```
{
  "type": "z",
  "blocks": [ "nether_portal:axis=z" ]
}
```
this would automatically connect all blocks in the list directly adjacent on the z axis, if looking at any of them.
```
{
  "type": "match",
  "rotate": "y",
  "required": true,
  "blocks": [
    [ "sunflower:half=upper" ],
    [ "sunflower:half=lower", "dirt" ],
    [ "grass_block" ]
  ]
}
```
this would connect all blocks if all are found in their respective positions on the grid (if looking at the lower half of the sunflower, there must be the upper half above, a dirt block next to it (any side since it may rotate on y axis) and a grass block below).

If it's not possible to get the shape of a block, this config could still specify it. It's not perfect but I just came up with these two examples to explain it. Possible problems include poor performance with a lot of rules and blocks to check, but should probably be fine.
This would allow users and modders to support the mod without API.

**Comment by LarsMans64** [comment]
already in the works :) it was actually already suggested by someone right after the first release

**Comment by LarsMans64** [comment]
The update is released! You can find documentation for the new way of adding outlines here: https://docs.teamdiopside.nl/seamless/
