### ISSUE TITLE
[1.18.2][Forge] Crash with Supplementaries java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by V972** [TeamDiopside/Seamless#7]
The crash blames Supplementaries, but it hapennes when I add Seamless.

I'm on lateast 1.18.2 Forge, Supplementaries and Seamless.

[crash-2023-09-13_00.26.04-fml.txt](https://github.com/TeamDiopside/Seamless/files/12591154/crash-2023-09-13_00.26.04-fml.txt)

**Comment by LarsMans64** [comment]
I am porting 2.0.0 to 1.18, which will fix this.
